language: php

php:
  - 5.3
  - 5.4
  - 5.5

env:
  global:
    - DATABASE='drupal'
    - DB_USERNAME='root'
    - DB_ENCODE='utf8'
    - MODULE_PATH='build/sites/all/modules/contrib'

mysql:
  database: $DATABASE
  username: $DB_USERNAME
  encoding: $DB_ENCODE

before_install:
  - pear channel-discover pear.drush.org

install:
  - pear install drush/drush-beta
  - phpenv rehash

before_script:
  - echo 'sendmail_path = /bin/true' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - drush --yes make tests/context_entity_field_test.make build
  - mkdir -p $MODULE_PATH
  - git archive $(git rev-parse --abbrev-ref HEAD) | tar -x -C $MODULE_PATH
  - cd build
  - drush --yes site-install standard --db-url="mysql://$DB_USERNAME@127.0.0.1/$DATABASE"
  - drush --yes en context_entity_field
  - drush --yes en simpletest

script:
  - drush test-run 'Context Entity Field'
